import React from 'react'

// Generated by IcoMoon.io

const ArrowRight = props => (
  <svg
    version="1.1"
    xmlns="http://www.w3.org/2000/svg"
    width="20"
    height="20"
    viewBox="0 0 32 32"
    fill={props.fill}
    className={props.className}
  >
    <title>arrow-left</title>
    <path d="M1 16l15 15v-9h16v-12h-16v-9z" />
  </svg>
)

export default ArrowRight
