import React from 'react'

// Generated by IcoMoon.io

const ArrowRight = props => (
  <svg
    version="1.1"
    xmlns="http://www.w3.org/2000/svg"
    width="20"
    height="20"
    viewBox="0 0 32 32"
    fill={props.fill}
    className={props.className}
  >
    <title>arrow-right</title>
    <path d="M31 16l-15-15v9h-16v12h16v9z" />
  </svg>
)

export default ArrowRight
